### ISSUE TITLE
Use SDB to determine the number of argument of a given function

### ISSUE THREAD

**Issue by Maijin** [radareorg/radeco#26]
`tmp = sym.imp.puts("Hello, world.", rsi, rdx, rcx, r8, r9)`
-> `anal/types/func.puts.args=1`
`tmp = sym.imp.puts("Hello, world.", rsi)`

**Comment by XVilka** [comment]
Should go to radeco-lib, please open next time in it

**Comment by Maijin** [comment]
https://github.com/radareorg/radeco-lib/issues/213 oki
