### ISSUE TITLE
Missing semi-colon ; at the end of instructions

### ISSUE THREAD

**Issue by Maijin** [radareorg/radeco#30]
Missing semi-colon ; at the end of instructions see:

![image](https://user-images.githubusercontent.com/1408600/44003406-7b4834dc-9e52-11e8-9c5f-01672b030927.png)

**Comment by XVilka** [comment]
Should go to radeco-lib, please open next time in it.

**Comment by XVilka** [comment]
https://github.com/radareorg/radeco-lib/issues/212
