### ISSUE TITLE
Provide a non-interactive way to decompile all functions

### ISSUE THREAD

**Issue by rfalke** [radareorg/radeco#45]
I'm comparing decompilers (see https://github.com/rfalke/decompiler-subjects). I would like to include radeco. However I failed so far to build a command line which decompiles all functions in the binary.

In tests/hello/Makefile there is "r2 -qc '#!pipe $(RADECO) -p $(STAGES)' hello" but it shows an interactive prompt. I expected something automatic from a test.

I found out that you can run "radeco <binary>" and then "analyze <function>" and then "decompile <function>". I would like that I can trigger this for functions in the binary.

I'm unsure if there is a difference between starting the r2 binary or the radeco binary.

I'm unsure if I have to specify the stages above and what is the recommended list.

In the end it is about adding a new update_radeco.sh script like the others in https://github.com/rfalke/decompiler-subjects/tree/master/scripts.

**Comment by rfalke** [comment]
And other thing: is there a switch to output C code and not Rust code?

**Comment by chinmaydd** [comment]
Hi @rfalke . First off, thank you creating this issue and getting in touch with us for including radeco in your list. Radeco for now only has an interactive mode for function decompilation. We have an open issue (#34) regarding your requirement and will work on it soon.

Also, (for now atleast) the radeco output is not meant to be C/Rust code but a high-level pseudocode for the binary.

**Comment by rfalke** [comment]
Good to know that you are plan to work on the non-interactive mode.

Regarding the output: yeah most decompiler aim at a C-like pseudocode. I was seeing "fn main ()" and "(0x0 as 32)". Both are rust (inspired).

**Comment by rfalke** [comment]
Looks like this was implemented. This issue can be closed from my side.

**Comment by Maijin** [comment]
@XVilka can you close here ?
