### ISSUE TITLE
Never panic

### ISSUE THREAD

**Issue by sushant94** [radareorg/radeco#47]
Error handling is currently not a strong point in radeco-lib. Sometimes we just need to accept that our analysis is imprecise and move forward to produce acceptable output rather than panicking. However, we would like to log all such errors to improve our analysis over time.

The framework to produce these logs when the `trace_log` feature is enabled is already in place. We need to convert all panics to appropriate Errors and handle them by logging these as warning and move on.

Since this involves going through a major part of radeco's code and understanding its architecture, this serves as a good stepping stone to contributing to radeco.

Some links: **TODO**

**Comment by kriw** [comment]
I'd like to work on this issue but there are unclear points for me.
* When `unwrap` (or something can panic) has failed and panic, should it return some appropriate value and should the program go on decompilation?

* If it should return some appropriate value when it fails, can the value be whatever?
(e.g if unwrap of Option<u8> value fails, it should return 0.

Thank you,

**Comment by sushant94** [comment]
@kriw So, there are two kinds of failures which can occur:

1. Failures that prevent us from making any progress (in a particular function, or the entire process)
2. Minor failures that may introduce bigs/imprecision but allow us to continue

For the first type, we want to return an `Error` (or, an `Option`) type from the function. The caller can then decide if it can continue (and log this), or abort.
For the second kind, we log it to error log (using `radeco_err!` macro).

I've made some progress with regards to this in the latest PR, but there is a lot more to be done.
I say we begin doing this from either a per-file or a per-module basis and work on it till we can standardize this/implement this across the entire library.

Feel free to discuss about this here :)

**Comment by kriw** [comment]
I made some progress, do you expect something like this ↓?
https://github.com/kriw/radeco-lib/commit/420be482472b8a4fdcef2c9f9880d4a5163ea41f

**Comment by kriw** [comment]
@sushant94 ping

**Comment by sushant94** [comment]
Oops, sorry this got past me. Checking it out.

**Comment by sushant94** [comment]
@kriw Yep, that would be the way to go.

But IMO, it is first important to decide which of the `unwrap` are allowed to fail, and we still make progress. For these, what you've done above is good, i.e. log the error and continue with defaults.

For others, we need to return an `Err` from the function. I think not finding the register state is not something you can recover from (as the SSA should have it, otherwise it would indicate an error in ssa construction).

**Comment by sushant94** [comment]
Done in #111 .
